name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      # - name: Lint
      #   id: npm-lint
      #   run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    needs: test-typescript
    environment: TEST

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   id: setup-node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 22

      - name: Test Local Action with Token Value Files
        id: test-action-files
        uses: ./
        with:
          files: ./test-files/*.txt
          tokenValueFiles: test-files/test.tkconf

      - name: Print Output token files
        id: output-files
        run: echo "${{ steps.test-action-files.outputs.changedFiles }}"

      - name: Test Local Action with Environment Variables
        id: test-action-env
        uses: ./
        with:
          files: ./test-files/*.tkn
          environment: TEST
          repo-token: ${{ secrets.GHTOKEN }}

      - name: Print Output env
        id: output-env
        run: echo "${{ steps.test-action-env.outputs.changedFiles }}"
